# docker-compose.yml

services:
  mongo_db:
    container_name: database
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo_db_database:/data/db
    ports:
      - "27017:27017"

  app1: 
    build:
      context: .
    container_name: netflix-movie-api
    ports:
      - "3001:3000"
    restart: always
    environment:
      APP_NAME: Netflix_Movie_API
      PORT: 3000
      DB_URI: mongodb://mongo_db:27017/netflix
    depends_on:
      - mongo_db
    # volumes:
    #   -

    

volumes:
  mongo_db_database:
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: ./volumes/mongodb/data/db

  redis_volume: 
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/redis/data