FROM node:18-alpine

WORKDIR /netflix_movie_api

# Copy only package files for dependency installation
COPY package*.json ./

RUN npm install

# Install nodemon globally for live reload
RUN npm install -g nodemon

# Copy all files
COPY . .

# EXPOSE 3000
# CMD ["npm", "run", "dev"]
# RUN node ./data/import-dev-data.js --import
